### ISSUE TITLE
Doesn't remember me

### ISSUE THREAD

**Issue by ZimiZones** [knapsu/plex-media-player-flatpak#4] opened 2020-07-13 07:13 UTC
Hi,
First, thanks for your work! I really appreciate it.
I have a problem, now I use flatpak installation on Ubuntu. Each time I run Plex, it asks me to put the code to link Plex as the first use.

Thanks

**Comment by ZimiZones** [comment] 2020-07-13 19:58
May be that is a permission issue. I had a problem during the installation, I had to change the rights on /var/tmp/ to be able to install using flatpak.. May be there is another folder I have to change the rights, so he would be able to save the information remembering me.

**Comment by knapsu** [comment] 2020-07-13 22:18
Hi. I cannot reproduce the issue. It works for me. I also think this must be a permission issue.

Please check `$HOME/.var/app/tv.plex.PlexMediaPlayer` directory permissions as `/home/user/.var/app` is the location where Flatpak applications will be saving it's data.

**Comment by Marc-Antoine** [comment] 2020-07-13 22:53
I did it recursively on `$HOME/.var/app/tv.plex.PlexMediaPlayer` but that didn't worked.. Is there a way to see the logs?

**Comment by ZimiZones** [comment] 2020-07-13 23:11
I did it recursively on $HOME/.var/app/tv.plex.PlexMediaPlayer but that didn't worked.. Is there a way to see the logs?

**Comment by knapsu** [comment] 2020-07-13 23:49
Logs will be in `$HOME/.var/app/tv.plex.PlexMediaPlayer/data/plexmediaplayer/logs` directory.

**Comment by ZimiZones** [comment] 2020-07-14 00:17
Ok so before I did a `chmod -R 1777` but that didn't work.
Looking at the logs I saw a lot of:
```
ERROR Could not write $HOME/.var/app/tv.plex.PlexMediaPlayer/data/plexmediaplayer/storage.json
ERROR Could not write $HOME/.var/app/tv.plex.PlexMediaPlayer/data/plexmediaplayer/...
```
I tried to only do a `chmod 777` on `$HOME/.var/app/tv.plex.PlexMediaPlayer/data/plexmediaplayer/storage.json` but still didn't work..
Finally I did a `chmod -R 777` on `$HOME/.var/app/tv.plex.PlexMediaPlayer/` and that worked.. Not really satisfied with that solution but it would be ok for now..

**Comment by knapsu** [comment] 2020-07-14 09:58
I do not know why you were setting sticky bit there when it is in your user home directory. Checked this in two systems and in both there were no sticky bits set for `.var/app`.
Just to be safe maybe running `chown` would also be good.

**Closed as completed by knapsu** 2020-07-14 09:58 UTC
